version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: agentmatch
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: agentmatch_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://agentmatch:secret@db:5432/agentmatch_dev
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8000/api

volumes:
  db_data:
