services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: channel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: channel_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://channel:secret@db:5432/channel_dev
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    
    command: npm run dev -- --host 0.0.0.0
    working_dir: /app
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules 

volumes:
  db_data:
